# Generated by Django 3.0.4 on 2020-04-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('Arizona Diamondbacks', 'Ari'), ('Atlanta Braves', 'Atl'), ('Baltimore Orioles', 'Blt'), ('Boston Red Sox', 'Bos'), ('Chicago White Sox', 'Cws'), ('Chicago Cubs', 'Chi'), ('Cincinnati Reds', 'Cin'), ('Cleveland Indians', 'Cle'), ('Colorado Rockies', 'Col'), ('Detroit Tigers', 'Det'), ('Houston Astros', 'Hou'), ('Kansas City Royals', 'Kcr'), ('Los Angeles Angels', 'Laa'), ('Los Angeles Dodgers', 'Lad'), ('Miami Marlins', 'Mia'), ('Milwaukee Brewers', 'Mil'), ('Minnesota Twins', 'Min'), ('New York Yankees', 'Nyy'), ('New York Mets', 'Nym'), ('Oakland Athletics', 'Oak'), ('Philadelphia Phillies', 'Phi'), ('Pittsburgh Pirates', 'Pit'), ('San Diego Padres', 'Sdp'), ('San Francisco Giants', 'Sfg'), ('Seattle Mariners', 'Sea'), ('St. Louis Cardinals', 'Stl'), ('Tampa Bay Rays', 'Tbr'), ('Texas Rangers', 'Tex'), ('Toronto Blue Jays', 'Tor'), ('Washington Nationals', 'Wsh')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseBallCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Company')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
